In [154]:
'''
prompt:
Gere codigo python que se conecta na API do Gemini e submete um prompt.
'''

'\nprompt:\nGere codigo python que se conecta na API do Gemini e submete um prompt.\n'

In [155]:

'''
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline
import torch
import time
from transformers import BitsAndBytesConfig


def load_model(model_name):
    # Enable quantization using bitsandbytes (e.g., 4-bit)
    quantization_config = BitsAndBytesConfig(
        load_in_4bit=True,  # Enable 4-bit quantization
        bnb_4bit_compute_dtype=torch.float16,  # Use float16 for computations
        bnb_4bit_use_double_quant=True,  # Use double quantization for memory efficiency
        bnb_4bit_quant_type="nf4"  # Use normalized float4 for better accuracy
    )

    start_time = time.time()

    # Load tokenizer and quantized model
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        quantization_config=quantization_config,
        device_map="auto",  # Automatically map the model to available devices
    )

    # Create the pipeline
    pipe = pipeline(
        "text-generation",
        model=model,
        tokenizer=tokenizer,
        #device=0  # Use GPU (if available) for inference
    )

    end_time = time.time()
    elapsed_time = end_time - start_time

    print('MODEL LOADED!', elapsed_time, "secs")
    return pipe

'''

'\nfrom transformers import AutoTokenizer, AutoModelForCausalLM, pipeline\nimport torch\nimport time\nfrom transformers import BitsAndBytesConfig\n\n\ndef load_model(model_name):\n    # Enable quantization using bitsandbytes (e.g., 4-bit)\n    quantization_config = BitsAndBytesConfig(\n        load_in_4bit=True,  # Enable 4-bit quantization\n        bnb_4bit_compute_dtype=torch.float16,  # Use float16 for computations\n        bnb_4bit_use_double_quant=True,  # Use double quantization for memory efficiency\n        bnb_4bit_quant_type="nf4"  # Use normalized float4 for better accuracy\n    )\n\n    start_time = time.time()\n\n    # Load tokenizer and quantized model\n    tokenizer = AutoTokenizer.from_pretrained(model_name)\n    model = AutoModelForCausalLM.from_pretrained(\n        model_name,\n        quantization_config=quantization_config,\n        device_map="auto",  # Automatically map the model to available devices\n    )\n\n    # Create the pipeline\n    pipe = pipeline(\n        "text-generation",\n        model=model,\n        tokenizer=tokenizer,\n        #device=0  # Use GPU (if available) for inference\n    )\n\n    end_time = time.time()\n    elapsed_time = end_time - start_time\n\n    print(\'MODEL LOADED!\', elapsed_time, "secs")\n    return pipe\n\n'

In [156]:
#!pip install google-generativeai
#!pip install -q -U transformers accelerate bitsandbytes

In [157]:
with open("api_key.txt", "r") as f:
    API_KEY = f.read().strip().split("\n")[0]

In [158]:
from google.generativeai import list_models
import google.generativeai as genai

genai.configure(api_key=API_KEY)

for m in list_models():
    print(m.name)

models/embedding-gecko-001
models/gemini-2.5-pro-preview-03-25
models/gemini-2.5-flash
models/gemini-2.5-pro-preview-05-06
models/gemini-2.5-pro-preview-06-05
models/gemini-2.5-pro
models/gemini-2.0-flash-exp
models/gemini-2.0-flash
models/gemini-2.0-flash-001
models/gemini-2.0-flash-exp-image-generation
models/gemini-2.0-flash-lite-001
models/gemini-2.0-flash-lite
models/gemini-2.0-flash-lite-preview-02-05
models/gemini-2.0-flash-lite-preview
models/gemini-2.0-pro-exp
models/gemini-2.0-pro-exp-02-05
models/gemini-exp-1206
models/gemini-2.0-flash-thinking-exp-01-21
models/gemini-2.0-flash-thinking-exp
models/gemini-2.0-flash-thinking-exp-1219
models/gemini-2.5-flash-preview-tts
models/gemini-2.5-pro-preview-tts
models/learnlm-2.0-flash-experimental
models/gemma-3-1b-it
models/gemma-3-4b-it
models/gemma-3-12b-it
models/gemma-3-27b-it
models/gemma-3n-e4b-it
models/gemma-3n-e2b-it
models/gemini-flash-latest
models/gemini-flash-lite-latest
models/gemini-pro-latest
models/gemini-2.5-flash-lite
models/gemini-2.5-flash-image-preview
models/gemini-2.5-flash-image
models/gemini-2.5-flash-preview-09-2025
models/gemini-2.5-flash-lite-preview-09-2025
models/gemini-3-pro-preview
models/gemini-3-pro-image-preview
models/nano-banana-pro-preview
models/gemini-robotics-er-1.5-preview
models/gemini-2.5-computer-use-preview-10-2025
models/embedding-001
models/text-embedding-004
models/gemini-embedding-exp-03-07
models/gemini-embedding-exp
models/gemini-embedding-001
models/aqa
models/imagen-4.0-generate-preview-06-06
models/imagen-4.0-ultra-generate-preview-06-06
models/imagen-4.0-generate-001
models/imagen-4.0-ultra-generate-001
models/imagen-4.0-fast-generate-001
models/veo-2.0-generate-001
models/veo-3.0-generate-001
models/veo-3.0-fast-generate-001
models/veo-3.1-generate-preview
models/veo-3.1-fast-generate-preview
models/gemini-2.0-flash-live-001
models/gemini-live-2.5-flash-preview
models/gemini-2.5-flash-live-preview
models/gemini-2.5-flash-native-audio-latest
models/gemini-2.5-flash-native-audio-preview-09-2025

In [159]:
import google.generativeai as genai



model_name = "gemini-2.5-flash"

# Configura a API
genai.configure(api_key=API_KEY)

# Cria o modelo
model = genai.GenerativeModel(model_name)

# Submete o prompt
prompt = "Explique a teoria da relatividade em termos simples"
#response = model.generate_content(prompt)

# Exibe a resposta
#print(response.text)

In [160]:
import pandas as pd

# Caminho para o arquivo CSV

language = 'portuguese'
caminho_csv = f"../data/processed/oab_with_firac_{language}_shuffle.csv"  

# Lê o CSV em um DataFrame
oab_questions_df = pd.read_csv(caminho_csv)

# Visualiza as primeiras linhas
oab_questions_df.head()

,question_id,pdf_filename,materia,oab_test_id,oab_question_id,language,enunciado,A,justificativa_A,B,...,D,justificativa_D,Facts,Issue,Rule,Application,Conclusion,correct_option,fact_count,rule_count
0,oab-1.pdf-001,oab-1.pdf,ÉTICA PROFISSIONAL,XV,1,Portuguese,Abelardo é magistrado vinculado ao Tribunal de...,O afastamento temporário do cargo que gera a i...,Afirmação falsa. A incompatibilidade persiste ...,A incompatibilidade com a advocacia persiste m...,...,A incompatibilidade permanece mesmo que ocorra...,"Alternativa correta. Conforme o art. 28, §1º, ...","[\n ""Abelardo é magistrado vinculado ao Tribu...",Um magistrado em licença temporária para trata...,"{""constituicao_federal"": [{""numero"": ""Art. 95,...",Abelardo é um magistrado que obteve licença pa...,A incompatibilidade para o exercício da advoca...,D,5,3
1,oab-1.pdf-002,oab-1.pdf,ÉTICA PROFISSIONAL,XV,2,Portuguese,"Fred, jovem advogado, é contratado para presta...",deve apresentar seu parecer ao conjunto de adv...,Afirmação falsa. Não há necessidade de deliber...,pode recusar-se a propor a ação diante do pare...,...,pode opor-se e postular assessoria da OAB.,Afirmação falsa. Não há previsão legal para qu...,"[\n ""Fred, um jovem advogado, foi contratado ...","Nos termos do Código de Ética da Advocacia, qu...","{""constituicao_federal"": [], ""codigo_penal"": [...",O advogado possui liberdade e independência no...,O advogado pode recusar-se a propor a ação dia...,B,7,3
2,oab-1.pdf-003,oab-1.pdf,ÉTICA PROFISSIONAL,XV,3,Portuguese,O advogado Caio atuava representando os intere...,Tício não pode ajuizar tal ação porque o advog...,Alternativa correta. O advogado substabelecido...,"Tício não pode ajuizar tal ação porque, como C...",...,"Tício pode ajuizar tal ação, pois, embora não ...","Afirmação falsa. O advogado substabelecido, co...","[\n ""Um advogado, Caio, representava um clien...",Pode o advogado que recebeu substabelecimento ...,"{""constituicao_federal"": [], ""codigo_penal"": [...",Os honorários advocatícios de êxito são devido...,O advogado que recebeu substabelecimento com r...,A,6,4
3,oab-1.pdf-004,oab-1.pdf,ÉTICA PROFISSIONAL,XV,4,Portuguese,"Os advogados X de Souza, Y dos Santos e Z de A...","É possível manter, pelo prazo máximo de seis m...",Afirmação falsa. O EAOAB não fixa qualquer pra...,É absolutamente vedada a manutenção do nome do...,...,"É possível manter o nome do sócio falecido, in...",Afirmação falsa. Para manter o nome do sócio f...,"[\n ""Os advogados X de Souza, Y dos Santos e ...",É juridicamente permitido manter o nome de um ...,"{""constituicao_federal"": [], ""codigo_penal"": [...",A legislação aplicável permite a permanência d...,É possível manter o nome do sócio falecido na ...,C,4,1
4,oab-1.pdf-005,oab-1.pdf,ÉTICA PROFISSIONAL,XIV,5,Portuguese,Matheus é estagiário vinculado ao escritório R...,"A renúncia ao mandato, sem respeitar o prazo l...",Afirmação falsa para FGV. A renúncia ao mandat...,O advogado pode afastar-se do processo em que ...,...,A renúncia aos poderes conferidos no mandato d...,Afrirmação falsa. A renúnca configura ato unil...,"[\n ""Matheus, um estagiário vinculado ao escr...",Quais são os requisitos legais e as implicaçõe...,"{""constituicao_federal"": [], ""codigo_penal"": [...",Considerando a decisão do escritório de renunc...,A renúncia do mandato por parte do escritório ...,C,3,2

In [161]:
oab_questions_df = oab_questions_df[
    (oab_questions_df['materia'].isin(['DIREITO CIVIL', 'DIREITOS HUMANOS'])) &
    (oab_questions_df['rule_count'].isin([1, 4])) 
    #(oab_questions_df['fact_count'].isin([1, 4]))
]

oab_questions_df.head()

,question_id,pdf_filename,materia,oab_test_id,oab_question_id,language,enunciado,A,justificativa_A,B,...,D,justificativa_D,Facts,Issue,Rule,Application,Conclusion,correct_option,fact_count,rule_count
558,oab-153.pdf-007,oab-153.pdf,DIREITO CIVIL,II,7,Portuguese,Com relação ao regime da solidariedade passiva...,as exceções podem ser aproveitadas por qualque...,Afirmação falsa. De acordo com o art. 281 do C...,cada herdeiro pode ser demandado pela dívida t...,...,com a perda do objeto por culpa de um dos deve...,Alternativa correta. Nos termos do art. 279 do...,"[\n ""A existência de um regime de solidarieda...",Qual a correta aplicação das regras do regime ...,"{""constituicao_federal"": [], ""codigo_penal"": [...",Ao analisar a responsabilidade em caso de fale...,"Em um regime de solidariedade passiva, os herd...",D,5,4
565,oab-153.pdf-014,oab-153.pdf,DIREITO CIVIL,II,14,Portuguese,João prometeu transferir a propriedade de uma ...,"a obrigação poderá ser resolvida, com a devolu...",Alternativa correta. Nos termos do art. 235 do...,"a obrigação fica resolvida, com a devolução de...",...,"a obrigação subsiste, com a entrega da coisa n...","Afirmação falsa, conforme comentário à alterna...","[\n ""João prometeu transferir a propriedade d...",Qual o regime jurídico aplicável à obrigação d...,"{""constituicao_federal"": [], ""codigo_penal"": [...","Considerando que uma coisa certa, objeto de pr...","A obrigação poderá ser resolvida, com a devolu...",A,3,1
569,oab-154.pdf-019,oab-154.pdf,DIREITO CIVIL,XV,19,Portuguese,Devido à indicação de luz vermelha do sinal de...,Tatiana e Sandro têm o dever de indenizar Rica...,Afirmação falsa. Sandro não terá de indenizar ...,Caberá a Tatiana indenizar os prejuízos causad...,...,"Cada um arcará com seu próprio prejuízo, visto...","Afirmação falsa. Tatiana, em razão de sua cond...","[\n ""Tatiana causou prejuízos aos veículos de...",Quem deve indenizar os prejuízos causados aos ...,"{""constituicao_federal"": [], ""codigo_penal"": [...",A responsabilidade civil pelos danos causados ...,Tatiana tem o dever de indenizar integralmente...,B,7,1
571,oab-154.pdf-021,oab-154.pdf,DIREITO CIVIL,XV,21,Portuguese,"Paulo foi casado, por muitos anos, no regime d...","No caso de confusão patrimonial, gerado pela c...",Alternativa correta. Admite-se a teoria da des...,É permitido ao juiz afastar os efeitos da pers...,...,Sabendo-se que a “teoria da desconsideração da...,Afirmação falsa. A Teoria Aplicada ao Código C...,"[\n ""Paulo foi casado com Luana, por muitos a...",É possível desconsiderar os atos de um dos côn...,"{""constituicao_federal"": [], ""codigo_penal"": [...",A conduta de transferir bens particulares para...,"Em casos de confusão patrimonial, gerada pela ...",A,5,4
573,oab-154.pdf-023,oab-154.pdf,DIREITO CIVIL,XV,23,Portuguese,"Mateus não tinha mais parentes, nunca tivera d...",Todo o patrimônio de Mateus caberá a Alberto.,Alternativa correta. Todo o patrimônio de Mate...,"Alberto terá direito à legítima, cabendo a Mar...",...,A herança de Mateus caberá igualmente aos três...,Afirmação falsa. A herança será integralmente ...,"[\n ""Mateus não possuía outros parentes, não ...",Diante da descoberta de um filho após a elabor...,"{""constituicao_federal"": [], ""codigo_penal"": [...","A regra aplicável estabelece que, se um descen...",Todo o patrimônio de Mateus caberá integralmen...,A,7,1

In [162]:
stats_df = (
    oab_questions_df
    .groupby('materia')
    .agg(
        count=('materia', 'count'),
        fact_count_median=('fact_count', 'median'),
        fact_count_mean=('fact_count', 'mean'),
        rule_count_median=('rule_count', 'median'),
        rule_count_mean=('rule_count', 'mean')
    )
    .reset_index()
)

stats_df

,materia,count,fact_count_median,fact_count_mean,rule_count_median,rule_count_mean
0,DIREITO CIVIL,109,5.0,5.733945,1.0,2.376147
1,DIREITOS HUMANOS,38,4.5,4.500000,1.0,2.026316

In [163]:
'''
import pandas as pd

# Caminho para o arquivo CSV
caminho_csv = "../data/processed/oab_guess_the_rule.csv"  # ou "oab.csv" se estiver na raiz do projeto

# Lê o CSV em um DataFrame
oab_guess_the_rule_df = pd.read_csv(caminho_csv)

# Visualizar as primeiras linhas
oab_guess_the_rule_df.head()
'''

'\nimport pandas as pd\n\n# Caminho para o arquivo CSV\ncaminho_csv = "../data/processed/oab_guess_the_rule.csv"  # ou "oab.csv" se estiver na raiz do projeto\n\n# Lê o CSV em um DataFrame\noab_guess_the_rule_df = pd.read_csv(caminho_csv)\n\n# Visualizar as primeiras linhas\noab_guess_the_rule_df.head()\n'

In [164]:
# Caminho para o arquivo
caminho_prompt_question = f"prompts/solve_question_prompt_{language}.txt"
caminho_prompt_guess_rule = "prompts/solve_question_rule_prompt.txt"

# Lê o conteúdo do arquivo como string
with open(caminho_prompt_question, "r", encoding="utf-8") as arquivo:
    prompt_text_question = arquivo.read()


# Lê o conteúdo do arquivo como string
with open(caminho_prompt_guess_rule, "r", encoding="utf-8") as arquivo:
    prompt_guess_rule = arquivo.read()

In [165]:
import json
import re

def normalize_json_like_string(s):
    # Primeiro: trocar aspas simples nas chaves por aspas duplas
    s = re.sub(r"'(\w+)'\s*:", r'"\1":', s)
    # Segundo: trocar aspas simples nos valores por aspas duplas,
    # mas sem mexer nas aspas que já são duplas
    s = re.sub(r":\s*'([^']*)'", r': "\1"', s)
    # Terceiro: trocar aspas simples dentro de listas ou dicionários
    s = re.sub(r"\[\s*'([^']*)'\s*\]", r'["\1"]', s)
    return s

import json

def get_leis(rules, conteudo):
    if conteudo == "numeros":
        rules = rules.replace("\"b\"", "b").replace("\'nı", "ni")
        #print('rules:', rules)
        rules = normalize_json_like_string(rules)

        # função recursiva para extrair valores de "lei"
        def extract_lei(o):
            if isinstance(o, dict):
                current = [o["numero"]] if "numero" in o else []
                children = sum((extract_lei(v) for v in o.values()), [])
                return current + children
            elif isinstance(o, list):
                return sum((extract_lei(v) for v in o), [])
            else:
                return []

        # extrai os valores
        leis = extract_lei(json.loads(rules))

        # filtra arrays vazios (não gerará entradas vazias)
        leis_filtradas = [l for l in leis if l]

        return ", ".join(map(str, leis_filtradas))
    else:
        return rules

leis = """ {'constituicao_federal': [], "codigo_penal": [], "codigo_processo_penal": [], "clt": [], "codigo_civil": [], "codigo_processo_civil": [], "codigo_direito_consumidor": [], "estatuto_crianca_adolescente": [], "sumula_stj": [], "estatuto_oab": [], "codigo_tributario_nacional": [{"numero": "Art. 132 do C\u00f3digo Tribut\u00e1rio Nacional", "conteudo": "A pessoa jur\u00eddica de direito privado que resultar de fus\u00e3o, transforma\u00e7\u00e3o ou incorpora\u00e7\u00e3o de outra ou em outra \u00e9 respons\u00e1vel pelos tributos devidos at\u00e9 \u00e0 data do ato pelas pessoas jur\u00eddicas de direito privado fusionadas, transformadas ou incorporadas."}, {"numero": "Art. 133, inciso I do C\u00f3digo Tribut\u00e1rio Nacional", "conteudo": "A responsabilidade do adquirente pelos tributos devidos pelo alienante at\u00e9 a data da aquisi\u00e7\u00e3o do estabelecimento empresarial \u00e9 integral e isolada, no caso de o alienante cessar a explora\u00e7\u00e3o da atividade."}, {"numero": "Art. 133, inciso II do C\u00f3digo Tribut\u00e1rio Nacional", "conteudo": "A responsabilidade do adquirente pelos tributos devidos pelo alienante at\u00e9 a data da aquisi\u00e7\u00e3o do estabelecimento empresarial \u00e9 subsidi\u00e1ria, se o alienante prosseguir na explora\u00e7\u00e3o da atividade ou, dentro de seis meses contados da data da aliena\u00e7\u00e3o, iniciar nova atividade no mesmo ou em outro ramo de com\u00e9rcio, ind\u00fastria ou profiss\u00e3o."}], "principio_geral_do_direito": [], "outros": []}"""
leis_obtidas = get_leis(leis, "numeros")
assert leis_obtidas == 'Art. 132 do Código Tributário Nacional, Art. 133, inciso I do Código Tributário Nacional, Art. 133, inciso II do Código Tributário Nacional'

#get_leis("""{"constituicao_federal": {"lei": ["Art. 5\u00ba, LIX, da Constitui\u00e7\u00e3o Federal de 1988"], "conteudo": ["ser\u00e1 admitida a\u00e7\u00e3o privada nos crimes de a\u00e7\u00e3o p\u00fablica, se esta n\u00e3o for intentada no prazo legal"]}, "codigo_penal": {"lei": [], "conteudo": []}, "codigo_processo_penal": {"lei": ["Art. 29 do C\u00f3digo de Processo Penal"], "conteudo": ["Ser\u00e1 admitida a\u00e7\u00e3o privada nos crimes de a\u00e7\u00e3o p\u00fablica, se esta n\u00e3o for intentada no prazo legal, cabendo ao Minist\u00e9rio P\u00fablico aditar a queixa, repudi\u00e1-la e oferecer den\u00fancia substitutiva, intervir em todos os termos do processo, fornecer elementos de prova, interpor recurso e, a todo tempo, no caso de neglig\u00eancia do querelante, retomar a a\u00e7\u00e3o como parte principal."]}, "clt": {"lei": [], "conteudo": []}, "codigo_civil": {"lei": [], "conteudo": []}, "codigo_processo_civil": {"lei": [], "conteudo": []}, "codigo_direito_consumidor": {"lei": [], "conteudo": []}, "estatuto_crianca_adolescente": {"lei": [], "conteudo": []}, "sumula_stj": {"lei": [], "conteudo": []}, "estatuto_oab": {"lei": [], "conteudo": []}, "codigo_tributario_nacional": {"lei": [], "conteudo": []}, "principio_geral_do_direito": {"lei": [], "conteudo": []}, "outros": {"lei": [], "conteudo": []}}""", "nomes")


# get_leis("""{"constituicao_federal": [], "codigo_penal": [], "codigo_processo_penal": [], "clt": [{"lei": "Art. 852-A", "conteudo": "Os diss\u00eddios individuais cujo valor n\u00e3o exceda a quarenta vezes o sal\u00e1rio m\u00ednimo vigente na data do ajuizamento da reclama\u00e7\u00e3o ficam submetidos ao procedimento sumar\u00edssimo."}, {"lei": "Art. 852-A, par\u00e1grafo \u00fanico", "conteudo": "Est\u00e3o exclu\u00eddas do procedimento sumar\u00edssimo as demandas em que \u00e9 parte a Administra\u00e7\u00e3o P\u00fablica direta, aut\u00e1rquica e fundacional."}], "codigo_civil": [], "codigo_processo_civil": [], "codigo_direito_consumidor": [], "estatuto_crianca_adolescente": [], "sumula_stj": [], "estatuto_oab": [], "codigo_tributario_nacional": [], "principio_geral_do_direito": [{"lei": "N/A", "conteudo": "A escolha do rito processual \u00e9 mat\u00e9ria de ordem p\u00fablica, n\u00e3o cabendo \u00e0 parte a op\u00e7\u00e3o."}], "outros": [{"lei": "N/A", "conteudo": "A exist\u00eancia de litiscons\u00f3rcio passivo, por si s\u00f3, n\u00e3o obriga a ado\u00e7\u00e3o do rito ordin\u00e1rio."}, {"lei": "N/A", "conteudo": "Quando a Fazenda P\u00fablica figurar no polo passivo, a a\u00e7\u00e3o deve obrigatoriamente seguir o rito ordin\u00e1rio, independentemente do valor da causa."}]}""", "nomes")

#get_leis("""{"constituicao_federal": {"lei": ["Art. 5\u00ba, LIX, da Constitui\u00e7\u00e3o Federal de 1988"], "conteudo": ["ser\u00e1 admitida a\u00e7\u00e3o privada nos crimes de a\u00e7\u00e3o p\u00fablica, se esta n\u00e3o for intentada no prazo legal"]}, "codigo_penal": {"lei": [], "conteudo": []}, "codigo_processo_penal": {"lei": ["Art. 29 do C\u00f3digo de Processo Penal"], "conteudo": ["Ser\u00e1 admitida a\u00e7\u00e3o privada nos crimes de a\u00e7\u00e3o p\u00fablica, se esta n\u00e3o for intentada no prazo legal, cabendo ao Minist\u00e9rio P\u00fablico aditar a queixa, repudi\u00e1-la e oferecer den\u00fancia substitutiva, intervir em todos os termos do processo, fornecer elementos de prova, interpor recurso e, a todo tempo, no caso de neglig\u00eancia do querelante, retomar a a\u00e7\u00e3o como parte principal."]}, "clt": {"lei": [], "conteudo": []}, "codigo_civil": {"lei": [], "conteudo": []}, "codigo_processo_civil": {"lei": [], "conteudo": []}, "codigo_direito_consumidor": {"lei": [], "conteudo": []}, "estatuto_crianca_adolescente": {"lei": [], "conteudo": []}, "sumula_stj": {"lei": [], "conteudo": []}, "estatuto_oab": {"lei": [], "conteudo": []}, "codigo_tributario_nacional": {"lei": [], "conteudo": []}, "principio_geral_do_direito": {"lei": [], "conteudo": []}, "outros": {"lei": [], "conteudo": []}}""", "nomes")

#get_leis(""" {"constituicao_federal": [], "codigo_penal": [], "codigo_processo_penal": [], "clt": [], "codigo_civil": [], "codigo_processo_civil": [], "codigo_direito_consumidor": [], "estatuto_crianca_adolescente": [], "sumula_stj": [], "estatuto_oab": [], "codigo_tributario_nacional": [{"lei": "Art. 132 do C\u00f3digo Tribut\u00e1rio Nacional", "conteudo": "A pessoa jur\u00eddica de direito privado que resultar de fus\u00e3o, transforma\u00e7\u00e3o ou incorpora\u00e7\u00e3o de outra ou em outra \u00e9 respons\u00e1vel pelos tributos devidos at\u00e9 \u00e0 data do ato pelas pessoas jur\u00eddicas de direito privado fusionadas, transformadas ou incorporadas."}, {"lei": "Art. 133, inciso I do C\u00f3digo Tribut\u00e1rio Nacional", "conteudo": "A responsabilidade do adquirente pelos tributos devidos pelo alienante at\u00e9 a data da aquisi\u00e7\u00e3o do estabelecimento empresarial \u00e9 integral e isolada, no caso de o alienante cessar a explora\u00e7\u00e3o da atividade."}, {"lei": "Art. 133, inciso II do C\u00f3digo Tribut\u00e1rio Nacional", "conteudo": "A responsabilidade do adquirente pelos tributos devidos pelo alienante at\u00e9 a data da aquisi\u00e7\u00e3o do estabelecimento empresarial \u00e9 subsidi\u00e1ria, se o alienante prosseguir na explora\u00e7\u00e3o da atividade ou, dentro de seis meses contados da data da aliena\u00e7\u00e3o, iniciar nova atividade no mesmo ou em outro ramo de com\u00e9rcio, ind\u00fastria ou profiss\u00e3o."}], "principio_geral_do_direito": [], "outros": []}""", "nomes")


#get_leis(""" {"constituicao_federal": [], "codigo_penal": [], "codigo_processo_penal": [], "clt": [], "codigo_civil": [], "codigo_processo_civil": [], "codigo_direito_consumidor": [], "estatuto_crianca_adolescente": [], "sumula_stj": [], "estatuto_oab": [], "codigo_tributario_nacional": [{"lei": "Art. 132 do C\u00f3digo Tribut\u00e1rio Nacional", "conteudo": "A pessoa jur\u00eddica de direito privado que resultar de fus\u00e3o, transforma\u00e7\u00e3o ou incorpora\u00e7\u00e3o de outra ou em outra \u00e9 respons\u00e1vel pelos tributos devidos at\u00e9 \u00e0 data do ato pelas pessoas jur\u00eddicas de direito privado fusionadas, transformadas ou incorporadas."}, {"lei": "Art. 133, inciso I do C\u00f3digo Tribut\u00e1rio Nacional", "conteudo": "A responsabilidade do adquirente pelos tributos devidos pelo alienante at\u00e9 a data da aquisi\u00e7\u00e3o do estabelecimento empresarial \u00e9 integral e isolada, no caso de o alienante cessar a explora\u00e7\u00e3o da atividade."}, {"lei": "Art. 133, inciso II do C\u00f3digo Tribut\u00e1rio Nacional", "conteudo": "A responsabilidade do adquirente pelos tributos devidos pelo alienante at\u00e9 a data da aquisi\u00e7\u00e3o do estabelecimento empresarial \u00e9 subsidi\u00e1ria, se o alienante prosseguir na explora\u00e7\u00e3o da atividade ou, dentro de seis meses contados da data da aliena\u00e7\u00e3o, iniciar nova atividade no mesmo ou em outro ramo de com\u00e9rcio, ind\u00fastria ou profiss\u00e3o."}], "principio_geral_do_direito": [], "outros": []}""", "conteudo")
#get_leis(""" {"constituicao_federal": [], "codigo_penal": [], "codigo_processo_penal": [], "clt": [], "codigo_civil": [], "codigo_processo_civil": [], "codigo_direito_consumidor": [], "estatuto_crianca_adolescente": [], "sumula_stj": [], "estatuto_oab": [], "codigo_tributario_nacional": [{"lei": "Art. 132 do C\u00f3digo Tribut\u00e1rio Nacional", "conteudo": "A pessoa jur\u00eddica de direito privado que resultar de fus\u00e3o, transforma\u00e7\u00e3o ou incorpora\u00e7\u00e3o de outra ou em outra \u00e9 respons\u00e1vel pelos tributos devidos at\u00e9 \u00e0 data do ato pelas pessoas jur\u00eddicas de direito privado fusionadas, transformadas ou incorporadas."}, {"lei": "Art. 133, inciso I do C\u00f3digo Tribut\u00e1rio Nacional", "conteudo": "A responsabilidade do adquirente pelos tributos devidos pelo alienante at\u00e9 a data da aquisi\u00e7\u00e3o do estabelecimento empresarial \u00e9 integral e isolada, no caso de o alienante cessar a explora\u00e7\u00e3o da atividade."}, {"lei": "Art. 133, inciso II do C\u00f3digo Tribut\u00e1rio Nacional", "conteudo": "A responsabilidade do adquirente pelos tributos devidos pelo alienante at\u00e9 a data da aquisi\u00e7\u00e3o do estabelecimento empresarial \u00e9 subsidi\u00e1ria, se o alienante prosseguir na explora\u00e7\u00e3o da atividade ou, dentro de seis meses contados da data da aliena\u00e7\u00e3o, iniciar nova atividade no mesmo ou em outro ramo de com\u00e9rcio, ind\u00fastria ou profiss\u00e3o."}], "principio_geral_do_direito": [], "outros": []}""", "nomes")



#get_leis(""" {'constituicao_federal': [], 'codigo_penal': [], 'codigo_processo_penal': [], 'clt': [], 'codigo_civil': [], 'codigo_processo_civil': [{'lei': "Medeni Usul Kanunu'nun 21. Maddesi, II. Fıkrası", 'conteudo': "yükümlülüğün Brezilya'da yerine getirilmesi gereken davaları işlemeye ve yargılamaya Brezilya yargı mercii yetkilidir."}], 'codigo_direito_consumidor': [], 'estatuto_crianca_adolescente': [], 'sumula_stj': [], 'estatuto_oab': [], 'codigo_tributario_nacional': [], 'principio_geral_do_direito': []}""", "nomes")
#get_leis(""" {'constituicao_federal': [], 'codigo_penal': [], 'codigo_processo_penal': [], 'clt': [], 'codigo_civil': [], 'codigo_processo_civil': [{'lei': "Medeni Usul Kanunu'nun 21. Maddesi, II. Fıkrası", 'conteudo': "yükümlülüğün Brezilya'da yerine getirilmesi gereken davaları işlemeye ve yargılamaya Brezilya yargı mercii yetkilidir."}], 'codigo_direito_consumidor': [], 'estatuto_crianca_adolescente': [], 'sumula_stj': [], 'estatuto_oab': [], 'codigo_tributario_nacional': [], 'principio_geral_do_direito': [], 'outros': [{"lei": 'aaa', "conteudo": 'bbb'}] } """, "nomes")

#get_leis(""" {'constituicao_federal': [], 'codigo_penal': [], 'codigo_processo_penal': [], 'clt': [], 'codigo_civil': [], 'codigo_processo_civil': [{'lei': 'Art. 554 do CPC/2015', 'conteudo': 'Zilyetlik davalarında değiştirilebilirlik (fungibilidade) özelliğini belirler; bu da bir zilyetlik davası yerine başka bir davanın açılmasının, yargıcın talebi incelemesine ve koşulları kanıtlanmış olana karşılık gelen yasal korumayı sağlamasına engel olmayacağı anlamına gelir.'}, {'lei': 'Art. 564, parágrafo único, do CPC/2015', 'conteudo': 'Ön gerekçelendirme emredildiğinde, cevap verme süresi, ihtiyati tedbir kararını veren veya reddeden tebliğden itibaren sayılır.'}, {'lei': 'Art. 555 do CPC/2015', 'conteudo': 'Zilyetlik talebiyle birlikte, zarar ve ziyanın tazmini, semerelerin tazmini ve yeni bir tecavüz veya gasp durumunda para cezası uygulanması gibi taleplerin birleştirilmesine izin verir.'}, {'lei': 'Art. 560 do CPC/2015', 'conteudo': 'Zilyetlik sahibinin tecavüz durumunda zilyetliğinde tutulma ve gasp durumunda zilyetliğin iadesi hakkına sahip olduğunu belirtir.'}], 'codigo_direito_consumidor': [], 'estatuto_crianca_adolescente': [], 'sumula_stj': [], 'estatuto_oab': [], 'codigo_tributario_nacional': [], 'principio_geral_do_direito': [], 'outros': []} """, "nomes")

#get_leis(""" {'constituicao_federal': [{'lei': '1988 Federal Anayasasının 146. maddesi, III. fıkrası, "b" bendi', 'conteudo': 'Tamamlayıcı yasaya düşen görev, vergi mevzuatı konusunda genel normları, yani vergilerin ve türlerinin tanımını, vergi doğuran olayları, matrahları, mükellefleri ile vergi yükümlülüğü, tahakkuk, alacak, zamanaşımı ve hak düşürücü süre konularını belirlemektir.'}], 'codigo_penal': [], 'codigo_processo_penal': [], 'clt': [], 'codigo_civil': [], 'codigo_processo_civil': [], 'codigo_direito_consumidor': [], 'estatuto_crianca_adolescente': [], 'sumula_stj': [], 'estatuto_oab': [], 'codigo_tributario_nacional': [], 'principio_geral_do_direito': [], 'outros': []} """, "nomes")

#get_leis(""" {'constituicao_federal': [{'lei': '1988 Federal Anayasası\'nın 146. maddesi, III. fıkrası, b bendi', 'conteudo': 'Tamamlayıcı yasaya düşen görev, vergi mevzuatı konusunda genel normları, yani vergilerin ve türlerinin tanımını, vergi doğuran olayları, matrahları, mükellefleri ile vergi yükümlülüğü, tahakkuk, alacak, zamanaşımı ve hak düşürücü süre konularını belirlemektir.'}], 'codigo_penal': [], 'codigo_processo_penal': [], 'clt': [], 'codigo_civil': [], 'codigo_processo_civil': [], 'codigo_direito_consumidor': [], 'estatuto_crianca_adolescente': [], 'sumula_stj': [], 'estatuto_oab': [], 'codigo_tributario_nacional': [], 'principio_geral_do_direito': [], 'outros': []} """, "nomes")

In [166]:
import json

def build_prompt(prompt_text, question_body, row, irac):

    if "G" in irac:
        return prompt_text + "\n" + question_body
    
    if "F" in irac:
        prompt_text = prompt_text.replace("""\"{{F}}\"""", row['Facts'])
    else:
        prompt_text = prompt_text.replace("""{{F}}""", "")

    if "I" in irac:
        #print(f"Vou adicionar issue: {row['Issue']}")
        prompt_text = prompt_text.replace("""{{I}}""", row['Issue'])
    else:
         prompt_text = prompt_text.replace("""{{I}}""", "")

    if "L" in irac:
        #print('rule', row['Rule'])
        rules = get_leis(row['Rule'], "numeros")
        prompt_text = prompt_text.replace("""{{R}}""", rules)
    elif "R" not in irac:
        prompt_text = prompt_text.replace("""{{R}}""", "")


    if "R" in irac:
        #print('rule', row['Rule'])
        rules = get_leis(row['Rule'], "conteudo")
        #print('rule', rules)
        prompt_text = prompt_text.replace("""{{R}}""", rules)
    elif "L" not in irac:
         prompt_text = prompt_text.replace("""{{R}}""", "")

    if "A" in irac:
        prompt_text = prompt_text.replace("""{{A}}""", row['Application'])
    else:
         prompt_text = prompt_text.replace("""{{A}}""", "")

    if "C" in irac:
        prompt_text = prompt_text.replace("""{{C}}""", row['Conclusion'])
    else:
        prompt_text = prompt_text.replace("""{{C}}""", "")

    return prompt_text.replace("{{questao}}", question_body)

In [167]:
import json
import ast

def corrigir_json_F_texto(json_texto):
    """
    Recebe um JSON em formato texto.
    Corrige o campo 'F' quando ele está como string com aspas simples.
    Retorna o JSON corrigido também como texto.
    """
    # 1. Carregar o JSON bruto
    dados = json.loads(json_texto)

    # 2. Tentar corrigir campo F
    if "F" in dados:
        valor = dados["F"]

        # Apenas se for string (erro comum)
        if isinstance(valor, str):
            try:
                lista = ast.literal_eval(valor)
                if isinstance(lista, list):
                    dados["F"] = lista
            except Exception:
                pass

    # 3. Retornar JSON corrigido como texto válido
    return json.dumps(dados, ensure_ascii=False, indent=2)

In [168]:
import json
import re

def load_json_safely(text):
    cleaned = re.sub(r'[\x00-\x08\x0B-\x0C\x0E-\x1F]', '', text)
    return json.loads(cleaned)

def test_load_json_safely():
    # JSON contendo caracteres de controle proibidos
    broken_json = (
        '{\n'
        '  "F": ["A existência de um regime\x0b de solidariedade passiva."],\n'
        '  "I": "Teste de controle\x0c aqui"\n'
        '}\n'
    )

    expected = {
        "F": ["A existência de um regime de solidariedade passiva."],
        "I": "Teste de controle aqui"
    }

    result = load_json_safely(broken_json)

    # Testa se removeu os caracteres e fez o parse corretamente
    assert result == expected, f"Resultado inesperado: {result}"

    print("Teste passou!")

# Executa o teste
if __name__ == "__main__":
    test_load_json_safely()

Teste passou!

In [ ]:
import pandas as pd
import time
from tqdm import tqdm
import os
import re

FINISH_REASONS = {
    0: "FINISH_REASON_UNSPECIFIED",
    1: "STOP",
    2: "MAX_TOKENS",
    3: "SAFETY",
    4: "RECITATION",
    5: "OTHER"
}

def run_exam(oab_questions_df, prompt, model_name, N=1, firac=""):
    assert oab_questions_df['question_id'].is_unique
    
    genai.configure(api_key=API_KEY)
    model = genai.GenerativeModel(model_name)

    output_path = f"../data/processed/model-runs/{language}/{model_name}_answers_firac-{firac}.csv"

    if os.path.exists(output_path):
        previous_answers_df = pd.read_csv(output_path)
        previous_answers_df = previous_answers_df[previous_answers_df['chosen_option'].notna() & 
                                          (previous_answers_df['chosen_option'] != '')].copy()

        assert previous_answers_df['question_id'].is_unique
        already_processed_ids = set(previous_answers_df["question_id"])
    else:
        previous_answers_df = pd.DataFrame()
        already_processed_ids = set()

    total_questions = len(oab_questions_df)
    processed_so_far = len(already_processed_ids)
    remaining = total_questions - processed_so_far
    percent_done = (processed_so_far / total_questions) * 100

    #print(f"--- Progresso atual --- {firac}")
    print(f"Já processadas: {processed_so_far} de {total_questions} [{language}] ({percent_done:.1f}%)")
    # print(f"Faltam: {remaining} questões de {language}")

    remaining_df = oab_questions_df[
        (~oab_questions_df["question_id"].isin(already_processed_ids))
        & ~(oab_questions_df["materia"] == "DIREITO PENAL")
    ]

    if remaining_df.empty:
        print("✅ Todas as questões já foram processadas.")
        return

    assert remaining_df['question_id'].is_unique

    amostra_df = (
        remaining_df
        .sort_values("question_id")
        .head(N)
        .reset_index(drop=True)
    )

    #amostra_df = remaining_df.sample(
    #    n=min(N, len(remaining_df)), replace=False, random_state=42,
    #).reset_index(drop=True)
    assert amostra_df['question_id'].is_unique

    new_answers_df = pd.DataFrame(columns=[
        "pdf_filename", "materia", "oab_test_id",
         "oab_question_id", "question_id", "enunciado",
        "A", "B", "C", "D",
        "full_response", "chosen_option", "correct_option", "response_time_seconds"
    ])

    for index, row in tqdm(amostra_df.iterrows(), total=len(amostra_df), desc=f"Executando questões {model_name}"):
        #print(f"Respondendo {row['question_id']}...")

        question_body = f'''
        {row['enunciado']}

        A) {row['A']}
        B) {row['B']}
        C) {row['C']}
        D) {row['D']}
        '''

        full_prompt = build_prompt(prompt, question_body, row, firac)
        print('prompt', full_prompt)
        #1/0

        # ⏱️ medir tempo de resposta do modelo
        print(f"vou executar: {row['question_id']} / {firac}", end = " ")
        start_time = time.time()
        response = model.generate_content(full_prompt)
        end_time = time.time()
        response_time = end_time - start_time

        if response.candidates[0].finish_reason == 5:
            resposta_texto = ''
        else:
            resposta_texto = response.text
            
        if resposta_texto.startswith("```"):
             #resposta_texto = resposta_texto.replace("\"['", '["').replace("']\"", '"]').replace("', '", '", "')
             #resposta_texto = resposta_texto.replace('\\', '\\\\')
             resposta_texto = "\n".join(resposta_texto.split("\n")[1:-1])  # remove ```json ... ```
             #resposta_texto = corrigir_json_F_texto(resposta_texto)
        
        print('executei e a resposta é:', resposta_texto)
        resposta_json = load_json_safely(resposta_texto)
        print("is_correct?", resposta_json['resposta'] == row['correct_option'])


        new_row_df = pd.DataFrame([{
            "pdf_filename": row['pdf_filename'],
            "language": row['language'],
            "question_id": row['question_id'],
            "materia": row['materia'],
            "oab_test_id": row['oab_test_id'],
            "oab_question_id": row['oab_question_id'],
            "chosen_option": resposta_json['resposta'],
            "correct_option": row['correct_option'],
            "is_correct": resposta_json['resposta'] == row['correct_option'],
            "enunciado": row['enunciado'],
            "prompt": full_prompt,
            "finish_reason": FINISH_REASONS.get(response.candidates[0].finish_reason, "UNKNOWN"),
            "avg_logprobs": response.candidates[0].avg_logprobs,
            "input_token_count": response.usage_metadata.prompt_token_count,
            "output_token_count": response.usage_metadata.candidates_token_count,
            
            "A": row['A'],
            "B": row['B'],
            "C": row['C'],
            "D": row['D'],
            "full_response": resposta_texto,
            "firac": firac,
            "Facts": resposta_json['F'],
            "Issue": resposta_json['I'],
            "Rule": resposta_json['R'],
            "Application": resposta_json['A'],
            "Conclusion": resposta_json['C'],
            "rule_count": row['rule_count'],
            "fact_count": row['fact_count'],
            "response_time_seconds": response_time  
        }])
    # Filtra dataframes vazios antes da concatenação
    frames = [f for f in [new_answers_df, new_row_df] if not f.empty and not f.isna().all().all()]
    new_answers_df = pd.concat(frames, ignore_index=True) if frames else new_row_df.copy()

    time.sleep(5)

    frames = [previous_answers_df, new_answers_df]
    # Mantém apenas DataFrames que não são vazios e não têm todas as colunas NaN
    frames = [f for f in frames if not f.empty and not f.isna().all().all()]
    updated_answers_df = pd.concat(frames, ignore_index=True) if frames else pd.DataFrame()
    
    assert updated_answers_df['question_id'].is_unique

    updated_answers_df.to_csv(output_path, index=False, encoding='utf-8-sig')

    processed_total = len(updated_answers_df)
    percent_final = (processed_total / total_questions) * 100
    print(f"\n✅ Processadas {len(new_answers_df)} novas questões.")
    print(f"📊 Total agora: {processed_total} de {total_questions} ({percent_final:.1f}%)")

In [170]:
from json import JSONDecodeError
import random
import time
from collections import defaultdict
from pprint import pprint

# Início da contagem de tempo
start_time = time.time()

firacs = ["____", "__L__", "F____", "__R__", "FI___", "FIL__", "FIR__", "FIRA_", "FIRAC"]
models = ["gemma-3-1b-it", "gemma-3-4b-it", "gemma-3-12b-it", "gemma-3-27b-it"] #"gemini-2.0-flash-lite", "gemini-2.0-flash", "gemini-2.5-flash-lite-preview-06-17", "gemini-2.5-flash", "gemini-2.5-flash-lite", "gemini-2.5-pro"]

firacs = ["FIRAC", "FIRA_", "FIR__", "FIL__", "FI___", "F____", "_____"]
firacs = ["FILA_", "FIL__", "FI___", "_____"]

models = ["gemini-2.0-flash-lite", "gemma-3-27b-it", "gemma-3-12b-it", "gemma-3-4b-it"] 

random.shuffle(firacs)
random.shuffle(models)

runs = 0
total_runs = len(firacs) * len(models) * oab_questions_df.shape[0]

print(f"Will run {len(firacs)} firacs x {len(models)} models x {oab_questions_df.shape[0]} questions = {total_runs} runs")

dic_model_stats = defaultdict(lambda: defaultdict(int))

for i in range(total_runs):
    for firac in firacs:
        print(f"\n** {firac} **")
        for model in models:
            runs += 1
            print(f"run {runs}/{total_runs}")
            try:
                run_exam(oab_questions_df, prompt_text_question, model, firac=firac)
                dic_model_stats[model]["OK"] += 1

            except JSONDecodeError as e:
                print(f"JSONDecodeError for model={model}, firac={firac}: {e}")
                dic_model_stats[model]["JSONDecodeError"] += 1
                1/0

            #    time.sleep(10)
            #    continue
            except KeyError as e:
                print(f"KeyError for model={model}, firac={firac}: {e}")
                dic_model_stats[model]["KeyError"] += 1

            print("*** stats ***")
            pprint(dict(sorted(dic_model_stats.items(),
                   key=lambda x: sum(x[1].values()),
                   reverse=True)))

# Fim da contagem de tempo
end_time = time.time()
elapsed = end_time - start_time

# Exibir tempo total formatado (em horas, minutos e segundos)
hours = int(elapsed // 3600)
minutes = int((elapsed % 3600) // 60)
seconds = int(elapsed % 60)

print(f"\nTempo total de execução: {hours}h {minutes}m {seconds}s ({elapsed:.2f} segundos)")

Will run 4 firacs x 4 models x 147 questions = 2352 runs

** FIL__ **
run 1/2352
Já processadas: 0 de 147 [portuguese] (0.0%)

Executando questões gemma-3-27b-it:   0%|          | 0/1 [00:00<?, ?it/s]

prompt Resolva a questão juridica abaixo considerando a legislação brasileira.
Você deve resolvê-la usando o framework de raciocínio jurídico FIRAC (Facts, Issues, Rules, Application, Conclusion).

Responda exclusivamente no formato JSON, sem markdown, com os seguintes campos, preenchendo de forma concisa e direta cada etapa FIRAC:
{{
 "F":[
  "A existência de um regime de solidariedade passiva em uma obrigação.",
  "A ocorrência da morte de um dos devedores solidários.",
  "A impossibilidade da prestação de uma obrigação solidária por culpa de um dos devedores.",
  "A ocorrência de atraso injustificado no cumprimento de uma obrigação solidária por culpa de um dos devedores.",
  "A possibilidade de um devedor solidário demandado opor exceções ao credor."
],
 "I": "Qual a correta aplicação das regras do regime da solidariedade passiva em diferentes cenários, especialmente no que tange à responsabilidade dos devedores, seus herdeiros, e a arguição de defesas?",
 "R": "Art. 276 do Código Civil, Art. 279 do Código Civil, Art. 280 do Código Civil, Art. 281 do Código Civil",
 "A": "",
 "C": "",
 "resposta": "A/B/C/D"
}}

Os campos F/I/R/A/C que já estão preenchidos não devem ser alterados e você deve usá-los como dicas para resolver a questão.
O campo "resposta" deve ser preenchido com a alternativa que você julga ser correta (A/B/C/D).

Questão:

        Com relação ao regime da solidariedade passiva, é correto afirmar que:

        A) as exceções podem ser aproveitadas por qualquer dos devedores solidários,
ainda que sejam pessoais apenas a um deles.
        B) cada herdeiro pode ser demandado pela dívida toda do devedor solidário
falecido.
        C) se houver atraso injustificado no cumprimento da obrigação por culpa de um
dos devedores solidários, a solidariedade subsiste no pagamento do valor
principal, mas pelos juros da mora somente poderá ser demandado o culpado.
        D) com a perda do objeto por culpa de um dos devedores solidários, a
solidariedade subsiste no pagamento do equivalente pecuniário, mas pelas
perdas e danos somente poderá ser demandado o culpado.

vou executar: oab-153.pdf-007 / FIL__

Executando questões gemma-3-27b-it:   0%|          | 0/1 [00:12<?, ?it/s]

executei e a resposta é: {
 "F":[
  "A existência de um regime de solidariedade passiva em uma obrigação.",
  "A ocorrência da morte de um dos devedores solidários.",
  "A impossibilidade da prestação de uma obrigação solidária por culpa de um dos devedores.",
  "A ocorrência de atraso injustificado no cumprimento de uma obrigação solidária por culpa de um dos devedores.",
  "A possibilidade de um devedor solidário demandado opor exceções ao credor."
],
 "I": "Qual a correta aplicação das regras do regime da solidariedade passiva em diferentes cenários, especialmente no que tange à responsabilidade dos devedores, seus herdeiros, e a arguição de defesas?",
 "R": "Art. 276 do Código Civil, Art. 279 do Código Civil, Art. 280 do Código Civil, Art. 281 do Código Civil",
 "A": "O art. 279 do CC estabelece que a solidariedade passiva permite que cada devedor seja demandado pela totalidade da dívida. No entanto, as exceções pessoais ao devedor não podem ser opostas aos demais (art. 281, CC).",
 "C": "A solidariedade passiva, conforme o art. 276 do CC, implica que cada devedor responde pela totalidade da dívida. A culpa de um devedor não exime os demais da responsabilidade pelo valor principal e acessórios (juros, correção monetária, etc.). O devedor culpado responderá também pelas perdas e danos.",
 "resposta": "C"
}

TypeError: the JSON object must be str, bytes or bytearray, not dict

In [ ]:
'''
import random

N = 10


firacs = ["G"]
models = ["gemini-1.5-flash-8b", "gemini-1.5-flash", "gemini-2.0-flash-lite", "gemini-2.0-flash", "gemini-2.5-flash-lite-preview-06-17", "gemini-2.5-flash", "gemini-2.5-pro"]
models = ["gemini-2.0-flash-lite", "gemini-2.0-flash", "gemini-2.5-flash-lite-preview-06-17", "gemini-2.5-flash"]


random.shuffle(firacs)
random.shuffle(models)

for i in range(0, N):
    for firac in firacs:
        print("**", firac, "**")
        for model in models:
            run_exam(oab_guess_the_rule_df, prompt_guess_rule, model, firac=firac)

'''